<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <AssemblyName>SeedPlacementRandomizer</AssemblyName>
    <RootNamespace>SeedPlacement.Desktop</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>..\SeedPlacement.App\Assets\icon.ico</ApplicationIcon>
    <BuiltInComInteropSupport>false</BuiltInComInteropSupport>
  </PropertyGroup>
  <PropertyGroup Condition="'$(RuntimeIdentifier)' != ''">
    <SelfContained>true</SelfContained>
    <PublishSingleFile>true</PublishSingleFile>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
    <DebugType>embedded</DebugType>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia.Desktop" Version="12.1.3" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\SeedPlacement.App\SeedPlacement.App.csproj" />
  </ItemGroup>
  <Target Name="DropPublishSymbols" AfterTargets="ComputeResolvedFilesToPublishList">
    <ItemGroup>
      <ResolvedFileToPublish Remove="@(ResolvedFileToPublish)" Condition="'%(Extension)' == '.pdb'" />
    </ItemGroup>
  </Target>
</Project>
